declare let currentSpellPage: number;
declare let filteredSpellsCache: any[];
declare const expandedSpells: Set<number>;
declare let editorSelectSavedRange: Range | null;
declare let floatingToolbarTarget: HTMLElement | null;
declare let floatingToolbarRange: Range | null;
declare let hideFloatingToolbarTimeout: number | null;
declare let floatingToolbarInteracting: boolean;
declare let floatingToolbarInitialized: boolean;
declare let currentContextTable: HTMLTableElement | null;
declare let currentContextLink: HTMLAnchorElement | null;
declare let contextToolbarsInitialized: boolean;
declare let editorHandlersInitialized: boolean;
declare const debouncedRenderSpells: any;
declare function renderSpells(): void;
declare function renderSpellCards(spells: any[]): string;
declare function renderLoadMoreButton(total: number, perPage: number): string;
declare function loadMoreSpells(): void;
declare function toggleSpellCard(id: number): void;
declare function expandAllSpells(): void;
declare function collapseAllSpells(): void;
declare function setSpellFilter(f: string): void;
declare function setSpellLevelFilter(f: string): void;
declare function setSpellSchoolFilter(f: string): void;
declare function onSpellRangeChange(): void;
declare function onSpellTimeChange(): void;
declare function onSpellDurationChange(): void;
declare function toggleMaterialField(): void;
declare function formatText(elementId: string, format: string, value?: string): void;
declare function setEditorFont(elementIdOrSelect: string | HTMLSelectElement, selectEl?: HTMLSelectElement): void;
declare function setEditorFontSize(elementIdOrSelect: string | HTMLSelectElement, selectEl?: HTMLSelectElement): void;
declare function clearEditorFormatting(elementId: string): void;
declare function setBorderFormat(elementId: string): void;
declare function setReadAloudFormat(elementId: string, style?: string): void;
declare function removeSelectionBorders(): void;
declare function initEditorPasteHandlers(): void;
declare function handleEditorKeydown(e: KeyboardEvent): void;
declare function handleEditorPaste(e: ClipboardEvent): void;
declare function escapeHtml(text: string): string;
declare function insertTable(rows?: number, cols?: number): void;
declare function updateStickyOffsets(): void;
declare function initFloatingToolbar(): void;
declare function handleSelectionChange(): void;
declare function hideFloatingToolbar(clearRange?: boolean): void;
declare function applyFloatingHighlight(color: string, editor: HTMLElement, savedRange: Range): void;
declare function initContextToolbars(): void;
declare function showTableContextToolbar(table: HTMLTableElement): void;
declare function hideTableContextToolbar(): void;
declare function showLinkContextToolbar(link: HTMLAnchorElement): void;
declare function hideLinkContextToolbar(): void;
declare function hideContextToolbars(): void;
declare function getSpellClassesFromCheckboxes(): string[];
declare function setSpellClassesCheckboxes(classes: string[]): void;
declare function editSpell(id: number): void;
declare function clearSpellForm(): void;
//# sourceMappingURL=spell-editor.d.ts.map