interface TestResult {
    name: string;
    pass: boolean;
    detail: string;
    category: string;
}
declare const D: any;
declare const log: any;
declare const StorageAPI: any;
declare const STORAGE_KEY: any;
declare const renderAll: any;
declare const renderSpells: any;
declare const renderParty: any;
declare const renderWiki: any;
declare const renderMindmap: any;
declare const renderEmptyState: any;
declare const populateFilterDropdown: any;
declare const updateCounters: any;
declare const undoStack: any;
declare const redoStack: any;
declare const EventDelegation: any;
declare const ENTITY_TYPE_CONFIG: any;
declare const renderEntityLink: any;
declare const ErrorHandler: any;
declare const ENTITY_SCHEMAS: any;
declare const safeJSONParse: any;
declare const safeJSONStringify: any;
declare const repairDataArrays: any;
declare const validateDataIntegrity: any;
declare const PerformanceManager: any;
declare const debounce: any;
declare const throttle: any;
declare const setTheme: any;
declare const undo: any;
declare const redo: any;
declare const pushUndo: any;
declare const QREF_CONDITIONS: any;
declare const toggleQuickRef: any;
declare const applyQrefCondition: any;
declare const rollQrefDice: any;
declare const qrefSearch: any;
declare const toggleEventLog: any;
declare const clearEventLog: any;
declare const parseWikiLinks: any;
declare const navigateToWikiEntry: any;
declare const addNode: any;
declare const saveNodeFromModal: any;
declare const selectNodeType: any;
declare function clearTestData(): void;
declare function clearAllSpells(): void;
declare function clearAllWiki(): void;
declare function clearMindmap(): void;
declare const clearAllNodes: typeof clearMindmap;
declare function runAllTests(): TestResult[];
declare function runFeatureTests(silent?: boolean): TestResult[];
declare function runNewFeatureTests(silent?: boolean): TestResult[];
declare function runEntitySystemTests(silent?: boolean): TestResult[];
declare function runErrorHandlingTests(silent?: boolean): TestResult[];
declare function runPerformanceTests(silent?: boolean): TestResult[];
declare function runPerformanceTest(): void;
declare function runUITests(silent?: boolean): TestResult[];
declare function generateTestWiki(count?: number): void;
declare function generateTestMindmap(count?: number): void;
declare function testWikiSystem(): void;
declare function testWikiLinks(): void;
declare function testNetworkSystem(): void;
declare function testNodeTypes(): void;
declare function testQuickReference(): void;
declare function testEventLog(): void;
declare function testUndoRedo(): void;
declare function testAutoSave(): void;
declare function testIndexedDB(): void;
declare function completeReset(): Promise<void>;
declare let debugLog: string[];
declare function debugLogAdd(message: string): void;
declare function renderDebugLog(): void;
declare function clearDebugLog(): void;
declare function showDebugModal(): void;
declare function updateDebugStats(): void;
declare function updateDebugSystemStatus(): void;
declare function runValidation(silent?: boolean): TestResult[];
//# sourceMappingURL=debug.d.ts.map