declare const D: any;
declare const renderParty: any;
declare const renderQuests: any;
declare const fuzzySearchFields: any;
declare const highlightMatch: any;
declare const getTypeIcon: any;
declare const timers: any;
declare const formatTime: any;
declare const debouncedRenderParty: any;
declare const debouncedRenderQuests: any;
declare const lazyLoadObserver: IntersectionObserver;
declare function toggleMobileNav(): void;
declare function showMobileQuickNotes(): void;
declare function saveMobileQuickNotes(): void;
declare function showMobileSearch(): void;
declare function performMobileSearch(): void;
declare let draggedItem: HTMLElement | null;
declare let draggedList: HTMLElement | null;
declare function handleDragStart(e: DragEvent): void;
declare function handleDragEnd(e: DragEvent): void;
declare function handleDragOver(e: DragEvent): void;
declare function handleDrop(e: DragEvent): void;
//# sourceMappingURL=performance-extras.d.ts.map